### ISSUE TITLE
Ruby 3.2.6 investigation

### ISSUE THREAD

**Issue by Sudrien** [PierreRambaud/gemirro#90]
I have been trying to get things going in Ruby 3.2.6 - This is from a rvm install on Debian 12

These are my findings so far

-  There is a unless defined?(Builder::XChar) test for Builder that fails unless I have require 'builder' in my config.rb - even a bundle exec doesn't fix this.
- https://github.com/porter77/sinatra-static-assets is required due to old File.exists? calls
- Marshal.load(::Gem.inflate(uz_file.read)) should now be Marshal.load(::Gem::Util.inflate(uz_file.read)) - It was a two levels deep wrapper at least

Your work shows progress during a reindex. I really needed this. Thank you.

(Moved from another issue reply - it looked closer on first glance than it actually was)

**Comment by Sudrien** [comment]
/versions - which bundler will use - is unimplemented - which is referring to  https://github.com/rubygems/compact_index

`CompactIndex::GemVersion.new("0.9.8", "ruby", "abc123")` presumably can be parsed from the filename with just the Gem class

Any discussion I've found is too abstract to be useful

/api/v1/dependencies are dying badly

2025-01-10 18:45:21 - NoMethodError - undefined method `dependencies' for nil:NilClass:
        
                  dependencies = spec.dependencies.select do |d|
                                     ^^^^^^^^^^^^^
        /opt/gems/.rvm/gems/ruby-3.2.6/gems/gemirro-1.4.0/lib/gemirro/server.rb:226:in `block (2 levels) in gem_dependencies'

Is this due to somthing I did? Like allowing x.x version numbers? Doubtful. I'm still testing on too large a set of gems to evaluate this quickly. *sigh*


Without these api calls working the server bogs down horrendously

**Comment by PierreRambaud** [comment]
Hello :wave: 
I created this [PR](https://github.com/PierreRambaud/gemirro/pull/92), tell me if it's better for you.
I was able to run the server, download gems, index, etc.

**Comment by Sudrien** [comment]
I had to do a little more - early versions of bootstrap-sass were packaged without a gemspec.



> diff --git a/lib/gemirro/server.rb b/lib/gemirro/server.rb
> index 664b78c..e9d0dfa 100644
> --- a/lib/gemirro/server.rb
> +++ b/lib/gemirro/server.rb
> @@ -220,12 +220,17 @@ module Gemirro
>          gem_collection.compact!
>  
>          Parallel.map(gem_collection, in_threads: 4) do |gem, spec|
> -          dependencies = spec.dependencies.select do |d|
> -            d.type == :runtime
> -          end
>  
> -          dependencies = Parallel.map(dependencies, in_threads: 4) do |d|
> -            [d.name.is_a?(Array) ? d.name.first : d.name, d.requirement.to_s]
> +         if spec
> +            dependencies = spec.dependencies.select do |d|
> +              d.type == :runtime
> +            end
> +
> +            dependencies = Parallel.map(dependencies, in_threads: 4) do |d|
> +              [d.name.is_a?(Array) ? d.name.first : d.name, d.requirement.to_s]
> +            end
> +          else
> +            dependencies = []
>            end
>  
>            {

Note that https://blog.rubygems.org/2023/02/22/dependency-api-deprecation.html covers this api - compact_index is used now, if available.

**Comment by PierreRambaud** [comment]
It's weird, I've got no error when running this endpoint :( 
I updated the code to add a check over `spec`, if it's good for you, I can create a new release today

**Comment by Sudrien** [comment]
Still getting timeouts on Large installs

public/.cache is not pre-filled?  So are dependencies are figured out 4 threads at a time as part of the http request?

**Comment by PierreRambaud** [comment]
> Still getting timeouts on Large installs
> 
> public/.cache is not pre-filled? So are dependencies are figured out 4 threads at a time as part of the http request? ...sorry, 16 threads at a time at parts?

I don't really know, I did this project, ten years ago, and I haven't do Ruby since 👀 
I think there are many things to improve, if you think you can do it, I'll be glad to give you write access 👍

**Comment by Sudrien** [comment]
I would accept write access.

**Comment by Sudrien** [comment]
#91 Has been merged
